/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pft;

import javax.swing.UIManager;

/**
 *
 * @author mohammedsheikh
 */
public class MainClass extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public MainClass() {
        initComponents();
        savingGoalsPanel.setVisible(false);
        transactionsPanel.setVisible(false);
        dashboardPanel.setVisible(false);
        statisticsPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        statisticsButton = new javax.swing.JButton();
        savingGoalsButton = new javax.swing.JButton();
        transactionsButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        dasboardButton = new javax.swing.JButton();
        homePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dashboardPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        transactionsPanel = new javax.swing.JPanel();
        flexiOtherField = new javax.swing.JTextField();
        transactionsLabel = new javax.swing.JLabel();
        monthlyBudgetLabel = new javax.swing.JLabel();
        fixedExpensesLabel = new javax.swing.JLabel();
        rentLabel = new javax.swing.JLabel();
        contractsLabel = new javax.swing.JLabel();
        otherLabel = new javax.swing.JLabel();
        miscellaneousLabel = new javax.swing.JLabel();
        travelLabel = new javax.swing.JLabel();
        flexibleExpensesPanel = new javax.swing.JLabel();
        flexiTravelLabel = new javax.swing.JLabel();
        miscellaneousField = new javax.swing.JTextField();
        travelField = new javax.swing.JTextField();
        otherField = new javax.swing.JTextField();
        flexiTravelField = new javax.swing.JTextField();
        contractsField = new javax.swing.JTextField();
        monthlyBudgetField = new javax.swing.JTextField();
        rentField = new javax.swing.JTextField();
        flexiOtherLabel = new javax.swing.JLabel();
        transactionsSubmitButton = new javax.swing.JButton();
        savingGoalsPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        howMuchLabel = new javax.swing.JLabel();
        slider1 = new javax.swing.JSlider();
        enterManually1Label = new javax.swing.JLabel();
        enterManually1Field = new javax.swing.JTextField();
        howLongLabel = new javax.swing.JLabel();
        enterManually2Label = new javax.swing.JLabel();
        slider2 = new javax.swing.JSlider();
        enterManually2Field = new javax.swing.JTextField();
        savingGoalsSubmitButton = new javax.swing.JButton();
        statisticsPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        statisticsButton.setText("Statistics");
        statisticsButton.setPreferredSize(new java.awt.Dimension(150, 50));
        statisticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticsButtonActionPerformed(evt);
            }
        });

        savingGoalsButton.setText("Saving Goals");
        savingGoalsButton.setPreferredSize(new java.awt.Dimension(150, 50));
        savingGoalsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingGoalsButtonActionPerformed(evt);
            }
        });

        transactionsButton.setText("Transactions");
        transactionsButton.setPreferredSize(new java.awt.Dimension(150, 50));
        transactionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionsButtonActionPerformed(evt);
            }
        });

        homeButton.setText("Home");
        homeButton.setPreferredSize(new java.awt.Dimension(150, 50));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        dasboardButton.setText("Dashboard");
        dasboardButton.setPreferredSize(new java.awt.Dimension(150, 50));
        dasboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dasboardButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transactionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dasboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(savingGoalsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statisticsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dasboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(transactionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(savingGoalsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(statisticsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(buttonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, -1, -1));

        jLabel2.setText("home");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel2)
                .addContainerGap(365, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(475, Short.MAX_VALUE))
        );

        getContentPane().add(homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 600, 500));

        jLabel1.setText("dash");

        jButton4.setText("jButton4");

        jTextField3.setText("jTextField3");

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel1)
                .addContainerGap(369, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(150, 150, 150))
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jButton4)
                .addGap(58, 58, 58)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(326, Short.MAX_VALUE))
        );

        getContentPane().add(dashboardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 600, -1));

        transactionsPanel.setPreferredSize(new java.awt.Dimension(609, 497));

        transactionsLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        transactionsLabel.setText("Transactions");

        monthlyBudgetLabel.setText("Monthly Budget");

        fixedExpensesLabel.setText("Fixed Expenses");

        rentLabel.setText("Rent");

        contractsLabel.setText("Contracts");

        otherLabel.setText("Other");

        miscellaneousLabel.setText("Miscellaneous");

        travelLabel.setText("Travel");

        flexibleExpensesPanel.setText("Flexible Expenses");

        flexiTravelLabel.setText("Travel");

        flexiOtherLabel.setText("Other");

        transactionsSubmitButton.setText("Submit");
        transactionsSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionsSubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transactionsPanelLayout = new javax.swing.GroupLayout(transactionsPanel);
        transactionsPanel.setLayout(transactionsPanelLayout);
        transactionsPanelLayout.setHorizontalGroup(
            transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionsPanelLayout.createSequentialGroup()
                .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rentField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(transactionsPanelLayout.createSequentialGroup()
                            .addGap(250, 250, 250)
                            .addComponent(transactionsLabel))
                        .addGroup(transactionsPanelLayout.createSequentialGroup()
                            .addGap(250, 250, 250)
                            .addComponent(fixedExpensesLabel))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transactionsPanelLayout.createSequentialGroup()
                            .addGap(100, 100, 100)
                            .addComponent(monthlyBudgetLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(monthlyBudgetField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(transactionsPanelLayout.createSequentialGroup()
                            .addGap(270, 270, 270)
                            .addComponent(travelField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(transactionsPanelLayout.createSequentialGroup()
                            .addGap(250, 250, 250)
                            .addComponent(flexibleExpensesPanel))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transactionsPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(transactionsPanelLayout.createSequentialGroup()
                                    .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(contractsLabel)
                                        .addComponent(rentLabel)
                                        .addComponent(otherLabel)
                                        .addComponent(travelLabel))
                                    .addGap(72, 72, 72)
                                    .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(contractsField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(otherField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(transactionsPanelLayout.createSequentialGroup()
                                    .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(transactionsPanelLayout.createSequentialGroup()
                                            .addComponent(miscellaneousLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transactionsPanelLayout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(flexiOtherLabel)
                                                .addComponent(flexiTravelLabel))
                                            .addGap(72, 72, 72)))
                                    .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(flexiTravelField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(flexiOtherField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(miscellaneousField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(transactionsSubmitButton)
                .addGap(19, 19, 19))
        );
        transactionsPanelLayout.setVerticalGroup(
            transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(transactionsLabel)
                .addGap(28, 28, 28)
                .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthlyBudgetLabel)
                    .addComponent(monthlyBudgetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(fixedExpensesLabel)
                .addGap(25, 25, 25)
                .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentLabel))
                .addGap(18, 18, 18)
                .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contractsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contractsLabel))
                .addGap(18, 18, 18)
                .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(otherLabel)
                    .addComponent(otherField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(travelLabel)
                    .addComponent(travelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(flexibleExpensesPanel)
                .addGap(18, 18, 18)
                .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(flexiTravelLabel)
                    .addComponent(flexiTravelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flexiOtherField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flexiOtherLabel))
                .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transactionsPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(miscellaneousField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(miscellaneousLabel))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transactionsPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(transactionsSubmitButton)
                        .addContainerGap())))
        );

        getContentPane().add(transactionsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 590, 500));

        savingGoalsPanel.setPreferredSize(new java.awt.Dimension(609, 497));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setText("Saving Goals");

        howMuchLabel.setText("How Much to Save?");

        enterManually1Label.setText("Enter Manually");

        howLongLabel.setText("How Long?");

        enterManually2Label.setText("Enter Manually");

        savingGoalsSubmitButton.setText("Submit");
        savingGoalsSubmitButton.setLocation(new java.awt.Point(-32275, -32315));

        javax.swing.GroupLayout savingGoalsPanelLayout = new javax.swing.GroupLayout(savingGoalsPanel);
        savingGoalsPanel.setLayout(savingGoalsPanelLayout);
        savingGoalsPanelLayout.setHorizontalGroup(
            savingGoalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(savingGoalsPanelLayout.createSequentialGroup()
                .addGroup(savingGoalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(savingGoalsPanelLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jLabel4))
                    .addGroup(savingGoalsPanelLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(howMuchLabel)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(savingGoalsPanelLayout.createSequentialGroup()
                .addGroup(savingGoalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(savingGoalsPanelLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(savingGoalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterManually1Label)
                            .addComponent(enterManually1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(savingGoalsPanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(howLongLabel))))
                    .addGroup(savingGoalsPanelLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(savingGoalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(slider2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slider1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(savingGoalsPanelLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(savingGoalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterManually2Label)
                            .addComponent(enterManually2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, savingGoalsPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(savingGoalsSubmitButton)
                .addGap(16, 16, 16))
        );
        savingGoalsPanelLayout.setVerticalGroup(
            savingGoalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(savingGoalsPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addGap(33, 33, 33)
                .addComponent(howMuchLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(enterManually1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enterManually1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(howLongLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(slider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(enterManually2Label)
                .addGap(18, 18, 18)
                .addComponent(enterManually2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(savingGoalsSubmitButton)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(savingGoalsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 600, 500));

        statisticsPanel.setPreferredSize(new java.awt.Dimension(609, 497));

        jLabel5.setText("stats");

        jButton2.setText("jButton2");

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout statisticsPanelLayout = new javax.swing.GroupLayout(statisticsPanel);
        statisticsPanel.setLayout(statisticsPanelLayout);
        statisticsPanelLayout.setHorizontalGroup(
            statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statisticsPanelLayout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jLabel5)
                .addContainerGap(340, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statisticsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButton2)
                .addGap(88, 88, 88))
        );
        statisticsPanelLayout.setVerticalGroup(
            statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statisticsPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addGroup(statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statisticsPanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jButton2))
                    .addGroup(statisticsPanelLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(329, Short.MAX_VALUE))
        );

        getContentPane().add(statisticsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 610, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dasboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dasboardButtonActionPerformed
        
        dashboardPanel.setVisible(true);
        homePanel.setVisible(false);
        transactionsPanel.setVisible(false);
        savingGoalsPanel.setVisible(false);
        statisticsPanel.setVisible(false);
        savingGoalsButton.setEnabled(true);
        homeButton.setEnabled(true);
        dasboardButton.setEnabled(false);
        transactionsButton.setEnabled(true);
        statisticsButton.setEnabled(true);
    }//GEN-LAST:event_dasboardButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        dashboardPanel.setVisible(false);
        homePanel.setVisible(true);
        transactionsPanel.setVisible(false);
        savingGoalsPanel.setVisible(false);
        statisticsPanel.setVisible(false);
        savingGoalsButton.setEnabled(true);
        homeButton.setEnabled(false);
        dasboardButton.setEnabled(true);
        transactionsButton.setEnabled(true);
        statisticsButton.setEnabled(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void transactionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionsButtonActionPerformed
            dashboardPanel.setVisible(false);
        homePanel.setVisible(false);
        transactionsPanel.setVisible(true);
        savingGoalsPanel.setVisible(false);
        statisticsPanel.setVisible(false);
        savingGoalsButton.setEnabled(true);
        homeButton.setEnabled(true);
        dasboardButton.setEnabled(true);
        transactionsButton.setEnabled(false);
        statisticsButton.setEnabled(true);
    }//GEN-LAST:event_transactionsButtonActionPerformed

    private void savingGoalsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingGoalsButtonActionPerformed
       dashboardPanel.setVisible(false);
        homePanel.setVisible(false);
        transactionsPanel.setVisible(false);
        savingGoalsPanel.setVisible(true);
        statisticsPanel.setVisible(false);
        savingGoalsButton.setEnabled(false);
        homeButton.setEnabled(true);
        dasboardButton.setEnabled(true);
        transactionsButton.setEnabled(true);
        statisticsButton.setEnabled(true);
    }//GEN-LAST:event_savingGoalsButtonActionPerformed

    private void statisticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticsButtonActionPerformed
       dashboardPanel.setVisible(false);
        homePanel.setVisible(false);
        transactionsPanel.setVisible(false);
        savingGoalsPanel.setVisible(false);
        statisticsPanel.setVisible(true);
        savingGoalsButton.setEnabled(true);
        homeButton.setEnabled(true);
        dasboardButton.setEnabled(true);
        transactionsButton.setEnabled(true);
        statisticsButton.setEnabled(false);
    }//GEN-LAST:event_statisticsButtonActionPerformed

    private void transactionsSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionsSubmitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transactionsSubmitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
try {
            //here you can put the selected theme class name in JTattoo
            UIManager.setLookAndFeel("com.jtattoo.plaf.texture.TextureLookAndFeel");
 
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainClass().setVisible(true);
        });
        
  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JTextField contractsField;
    private javax.swing.JLabel contractsLabel;
    private javax.swing.JButton dasboardButton;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JTextField enterManually1Field;
    private javax.swing.JLabel enterManually1Label;
    private javax.swing.JTextField enterManually2Field;
    private javax.swing.JLabel enterManually2Label;
    private javax.swing.JLabel fixedExpensesLabel;
    private javax.swing.JTextField flexiOtherField;
    private javax.swing.JLabel flexiOtherLabel;
    private javax.swing.JTextField flexiTravelField;
    private javax.swing.JLabel flexiTravelLabel;
    private javax.swing.JLabel flexibleExpensesPanel;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel howLongLabel;
    private javax.swing.JLabel howMuchLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField miscellaneousField;
    private javax.swing.JLabel miscellaneousLabel;
    private javax.swing.JTextField monthlyBudgetField;
    private javax.swing.JLabel monthlyBudgetLabel;
    private javax.swing.JTextField otherField;
    private javax.swing.JLabel otherLabel;
    private javax.swing.JTextField rentField;
    private javax.swing.JLabel rentLabel;
    private javax.swing.JButton savingGoalsButton;
    private javax.swing.JPanel savingGoalsPanel;
    private javax.swing.JButton savingGoalsSubmitButton;
    private javax.swing.JSlider slider1;
    private javax.swing.JSlider slider2;
    private javax.swing.JButton statisticsButton;
    private javax.swing.JPanel statisticsPanel;
    private javax.swing.JButton transactionsButton;
    private javax.swing.JLabel transactionsLabel;
    private static javax.swing.JPanel transactionsPanel;
    private javax.swing.JButton transactionsSubmitButton;
    private javax.swing.JTextField travelField;
    private javax.swing.JLabel travelLabel;
    // End of variables declaration//GEN-END:variables
}
